
tasks:
  - name: Setup
    init: |
        pip install -r requirements.txt
        python -m textblob.download_corpora
        python check_env.py
vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
